CDAT/cdat.github.io

content/index.html
content/installing.html
content/media/css/tweaks.css
layout/base.j2
layout/footer.j2
layout/jumbotron.j2
layout/topbar.j2
site.yaml

Made a bunch of cosmetic tweaks, moved some links from the top of the site to the bottom, converted the carousel into a jumbotron, added some simple links based on user role, and changed around some of the HTML.

Bunch of improvements

---

content/index.html
layout/footer.j2
layout/topbar.j2

Also apparently forgot to do a PR on my moving the menu to be left-aligned again.

Conference announcement

---

content/documentation/cdms/cdms_3.html

Fixed bad indentation

---

content/index.html

Home Page Cleanup

---

index.md

ONLY MERGE WHEN 2.4 RELEASE IS FINALIZED

Updated release announcement to 2.4

---

_data/navlinks.yml
changelog.md
contact.md
index.md
releases/index.md

Fix for the bevvy of issues submitted by @jypeter, including #110 #108 and #106

Make Jean-Yves a Happy Camper

---

iPython/EasilyCreatingStringsWithTemplating/EasilyCreatingStringsWithTemplating.ipynb
iPython/EasilyCreatingStringsWithTemplating/EasilyCreatingStringsWithTemplating.md
tutorials.md

@mattben @chaosphere2112 no image on this one not sure what's the best way to handle it.

String ipython notebook

---

changelog.md
index.md
releases/index.md

Adds info about the 2.8 release to the site; @mattben please review and make sure I didn't mess anything up, then merge. I just dumped markdown into files; didn't try actually running jekyll.

2.8 release

---

index.md
installing.md

Modified two files to add links to the Getting Started guide so it is easier for new users to find.

DOC: make Getting Started guide more accessible

---

index.md
installing.md

Updating the index file to match the current situation.

Doc index update

---

installing.md

Added info about running CDAT on Windows 10.  Made other minor edits to improve readability.

DOC: updates to installing.html

---

getting_started.md
index.md
installing.md

Updated Getting Started guide.  Added information for those not familiar with Jupyter Notebooks.  Fixed a step in the example that was not working for me (path to sample data included folders /share/cdat/ ).

Doc getting started

---

contact.md

Updated the CDAT Contact Us page to make things a little clearer and to change email addresses to the new versions (cdat vs. uvcdat).

Doc contact us

---

tutorials.html

Updated CDAT tutorials page to include more information about Jupyter Notebooks, fix typos and make formatting of tutorial titles a little more uniform.

DOC: update tutorials page

---

Jupyter/PolarPlots/PolarPlots.html

Removed extra code that was showing up inappropriately on the Polar Plots Tutorial html page.  The code was likely markdown code that was not appropriate for the html page.

DOC: update polar plots tutorial

---

_tools/deploy.bash

Add '--recurse-submodules' to git pull command in deploy.bash to update Jupyter-notebooks submodule

Update deploy.bash to handle submodules

---

_data/navlinks.yml

fix getting started nav link

---

tutorials.html

Changes to Tutorials.html to add the VCS_Template Tutorial.

update to include VCS_Templates tutorial

---

tutorials.html

Added link to new notebook (VCS Basics); updated other links; provided .png files; made a few other text edits.
I tried to put @mauzey1 as a reviewer, but sadly Chris does not come up in my list of reviewers :(

add & update links

---

_includes/header.html
_includes/maintenance_banner.html

@davis278 @doutriaux1 Please review

Add maintenance banner for website outage on October 4-6, 2019

---

_includes/header.html
_includes/maintenance_banner.html

@davis278 Please review and merge

Remove banner for weekend website outage

---

tutorials.html

Add 4 new scientific notebooks to the CDAT Tutorials.html page.  Notebooks have been reviewed and approved in other pull requests in the Jupyter-notebooks repo.
@mauzey1 would you be so kind as to review this pull request?

add 4 new scientific notebooks

---

bsd-3-clause.txt

adding license file

---

README.md
tutorials.html

This renames current masks tutorial to 'advanced' and then adds a 'beginner' version. Updated the HTML of the webpage to include new tutorial.

Updates to add a beginner tutorial for masks.

---

_includes/footer.html

Add VDP link to footer
